# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          태인
baseurl:        "https://icecream0910.github.io/tale/"
url:            "https://icecream0910.github.io/tale/"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Ice Cream
  url:          taein2370@naver.com  
  github:       icecream0910
  twitter:      

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/icecream0910/tale

theme: jekyll-theme-cayman